version: 2.1

references:
  working_directory: &working_directory ~/repo
  attach_workspace: &attach_workspace
  image_name: &image_name 'circleci/python:3.7'
  node_image: &node_image
    image: circleci/node:14
  ipfs_image: &ipfs_image
    image: requestnetwork/request-ipfs
  ganache_image: &ganache_image
    image: trufflesuite/ganache-cli:v6.8.2
    command:
      - '-l'
      - '90000000'
      - '-m'
      - 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'

jobs:
  lint-package-json:
    docker:
      - *node_image
    working_directory: *working_directory
    steps:
      - checkout
      - run:
          name: Verify format
          command: sh scripts/collect.sh
      - run:
          name: Build types
          command: |
            cd packages/smart-contracts/
            ./soliumrc.sh
            
workflows:
  version: 2
  build-and-test:
    jobs:
      - lint-package-json